### ISSUE TITLE
Inference Code 

### ISSUE THREAD

**Issue by BigJoon** [snumprlab/isr-dpo#3]
Applauding your amazing research achievement. 
Is there still no inference code ready?

**Comment by Yuuraa** [comment]
Hi there! Thank you for your interest in our work.

To clarify, we have released the evaluation script for the video question answering benchmark, as mentioned in our [README](https://github.com/snumprlab/srt/tree/main?tab=readme-ov-file#evaluating-the-model). This script contains running the model inference and the GPT-4 evaluation. 

You can find the inference code in the following path: [Evaluation/inference//inference_test_qa.py](https://github.com/snumprlab/srt/tree/main/Evaluation/inference).

If you have any questions about the provided code, please don't hesitate to ask :)
